name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  open_meteo_api:
    path: ../open_meteo_api
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true